USE simplilearn;

-- Subqueries, Operators, and Derived Tables in SQL --

describe emp_records;
ALTER TABLE emp_records
MODIFY EMP_ID VARCHAR(10) NOT NULL PRIMARY KEY,
MODIFY FIRST_NAME VARCHAR(255) NOT NULL,
MODIFY LAST_NAME VARCHAR(255) NOT NULL,
MODIFY GENDER VARCHAR(10) NOT NULL,
MODIFY ROLE VARCHAR(100) NOT NULL,
MODIFY DEPARTMENT VARCHAR(100) NOT NULL,
MODIFY EXPERIENCE INT NOT NULL,
MODIFY COUNTRY VARCHAR(100) NOT NULL,
MODIFY CONTINENT VARCHAR(100) NOT NULL,
MODIFY SALARY INT NOT NULL,
MODIFY RATING INT NOT NULL,
MODIFY MANAGER_ID VARCHAR(10) NOT NULL;

describe proj_data;
ALTER TABLE proj_data
MODIFY PROJ_ID VARCHAR(10) NOT NULL PRIMARY KEY,
MODIFY PROJ_NAME VARCHAR(255) NOT NULL,
MODIFY DOMAIN VARCHAR(100) NOT NULL,
MODIFY START_DATE VARCHAR(100) NOT NULL,
MODIFY CLOSURE_DATE VARCHAR(100) NOT NULL,
MODIFY DEV_QTR VARCHAR(100) NOT NULL,
MODIFY STATUS VARCHAR(100) NOT NULL;

describe proj_assign;
ALTER TABLE proj_assign
MODIFY EMP_ID VARCHAR(10) NOT NULL,
MODIFY MANAGER_ID VARCHAR(10) NOT NULL,
MODIFY PROJ_ID VARCHAR(10) NOT NULL;

SET default_storage_engine=InnoDB;


