CREATE DATABASE SQL_FAMOUS_PAINTINGS;
USE SQL_FAMOUS_PAINTINGS;

SHOW TABLES;

-- ARTIST TABLE --
SELECT * FROM artist;
SELECT * FROM canvas_size;
SELECT * FROM image_link;
SELECT * FROM museum;
SELECT * FROM museum_hours;
SELECT * FROM product_size;
SELECT * FROM subject;
SELECT * FROM work;