CREATE DATABASE SQL_FAMOUS_PAINTINGS;
USE SQL_FAMOUS_PAINTINGS;

SHOW TABLES;

-- ARTIST TABLE --
SELECT * FROM artist;

-- CANVAS_SIZE TABLE --
SELECT * FROM canvas_size;

-- IMAGE_LINK TABLE --
SELECT * FROM image_link;

-- MUSEUM TABLE --
SELECT * FROM museum;

-- MUSEUM_HOURS TABLE --
SELECT * FROM museum_hours;

-- PRODUCT_SIZE TABLE --
SELECT * FROM product_size;